name: pdf_export_test
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  pdf: ^1.9.0
  path_provider: ^1.6.11
  open_file: ^3.0.1
  printing: ^3.5.0

  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
